name: Daily Cybersecurity Digest

on:
  schedule:
    - cron: "0 7 * * *"   # Runs every day at 08:00 UTC
  workflow_dispatch:  

jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Restore feeds.yaml from secret
        run: |
          echo "${{ secrets.FEEDS_YAML }}" | base64 -d > feeds.yaml

      - name: Run daily digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TITLE: ${{vars.TITLE}}
          SMTP_SERVER: ${{vars.SMTP_SERVER}}
          SMTP_PORT: ${{vars.SMTP_PORT}}
        run: |
          python -m briefme.main
